server.port=8082

application.url=http://authentication-app:8082

spring.application.name=authentication

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

token.signing.key=${JWT_TOKEN}
token.expiration.milliseconds=${JWT_TOKEN_EXPIRATION}

token.signing.refresh-key=${JWT_REFRESH_TOKEN}
token.expiration.refresh-milliseconds=${JWT_REFRESH_TOKEN_EXPIRATION}