FROM eclipse-temurin:24-jdk
WORKDIR /app

# Installa Maven
RUN apt-get update && apt-get install -y maven && apt-get clean

# Montiamo il codice da host, niente COPY
VOLUME /app

# Expose porta
EXPOSE 8081

# Comando per avviare Spring Boot in modalità sviluppo
CMD ["mvn", "spring-boot:run", "-Dspring-boot.run.profiles=dev"]
